### ISSUE TITLE
does this support openjdk8 for ubuntu 14.04?

### ISSUE THREAD

**Issue by hodiapa** [MetaCenterCloudPuppet/cesnet-java_ng#1]
Thanks for the awesome module . as per the request does this module support installation of openjdk8 on ubuntu 14.04?
As per this https://launchpad.net/ubuntu/+source/openjdk-8, openjdk8 version is not officially supported for the Ubuntu14.04.  A  ppa:openjdk-r/ppa is required to install on this platform.

reference: http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts/

**Comment by valtri** [comment]
It doesn't support it yet. But i would be nice feature, I'll try to add it.

**Comment by valtri** [comment]
Included in the the new version 2.0.0.
